### PR TITLE
Some proot fixes and improvements

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by corbinlc** [comment]
Can you describe tests cases that show why commits 5782d92 and b64a20d are needed?  Your work looks solid, but I would like to better understand the necessity, especially the first one.  Thanks!  Keep them coming!

**Comment by phcoder** [comment]
b64a20d: Try to do "ln -s whatever /usr" under unprivileged user. It should fail but without this patch it succeeds.
5782d92: AFFAIR try "sed -i 's,a,b,g' anyfile.txt". This creates a new file with permissions 000 and then moves it to anytime.txt

**Comment by phcoder** [comment]
5782d292: without patch you wouldn't be able to cat anytime.txt after this sed. All operations under unprivileged user.

**Comment by corbinlc** [comment]
For 578d92, when running the sed command and creating anyfile.txt, what directory are you in?

**Comment by phcoder** [comment]
Sponsored by:

 _____                   _
|_   _| ___  ___  ___  _| | _ _  ___  ___
  | |  | -_||  _|| . || . || | ||   || -_|
  |_|  |___||_|  |__,||___||_  ||_|_||___|
                           |___|

root@localhost:/# su -l phcoder
phcoder@localhost:~$ cd /tmp
phcoder@localhost:/tmp$ touch a.txt
phcoder@localhost:/tmp$ sed -i 's,a,b,' a.txt
phcoder@localhost:/tmp$ cat a.txt
cat: a.txt: Permission denied
phcoder@localhost:/tmp$

**Comment by corbinlc** [comment]
Sponsored by:

 _____                   _
|_   _| ___  ___  ___  _| | _ _  ___  ___
  | |  | -_||  _|| . || . || | ||   || -_|
  |_|  |___||_|  |__,||___||_  ||_|_||___|
                           |___|

root@localhost:/# cd /tmp
root@localhost:/tmp# touch a.txt
root@localhost:/tmp# sed -i 's,a,b,' a.txt
root@localhost:/tmp# cat a.txt
root@localhost:/tmp# ls -l
total 4
-rw-r--r--. 1 root root 0 Mar 12 06:59 a.txt
root@localhost:/tmp#


I get a different result.  Did you make other changes to GNURoot that may be causing it to behave different?

**Comment by phcoder** [comment]
You do it under root, I do it under my non-root user

**Comment by corbinlc** [comment]
Sorry, I missed that.  I figured I wasn't doing exactly what you were doing.

**Comment by corbinlc** [comment]
Ok, I can confirm that the issue exists.  I am guessing the fix will look a little different than what you did, but that is just a guess right now.  fake_id0, is supposed to modify the mode bits such that the case you ran into never occurs where the underlying file has 000 permissions.  You will see in fake_id0 where the mode gets modified like this:
```
mode = peek_reg(tracee, ORIGINAL, mode_sysarg);
poke_reg(tracee, mode_sysarg, (mode|0700));
```

**Comment by corbinlc** [comment]
Just got back to this.  The issue is that we need to fully emulate umask in fake_id0 and not allow umask calls to actually change to umask.  Once that is done, the underlying file cannot be created with no permissions.  I have it working locally.  I will now look at your other changes.  I wonder why no one stumbled into this before.  I really appreciate your help.  Need more people like you.

**Comment by corbinlc** [comment]
Isn't commit f8dda9b redundant given that line 12 in the same file has this:
LD = $(CC) -static
And the variable LD is used in the same line where you added -static?

**Comment by corbinlc** [comment]
Can you provide an example of why f823187 is needed like you did for a couple of the others?

**Comment by corbinlc** [comment]
I think I got all of your desired changes in and tested now.  Did it manually as I made some small changes, the largest of which being how I chose to deal with umask

**Pull request closed without merging**
